services:
  xinference:
    image: registry.lazycat.cloud/x/aipod/xinference:latest
    # 默认环境变量，注释后修改默认值即可应用，一般不需要更改
    # environment:
      # 模型来源，默认 modelscope，速度更快
      # - XINFERENCE_MODEL_SRC=modelscope
      # 如果下载部分模型提示没有 huggingface 仓库权限，请设置此环境变量
      # - HUGGING_FACE_HUB_TOKEN=
    ports:
      - "9997:9997"
    volumes:
      - ./.xinference:/app/.xinference
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]