[project]
name = "builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pip>=25.1.1",
    "pypiserver>=2.3.2",
    "requests>=2.32.3",
    "uv>=0.7.5",
]
